import type { ReactNode } from "react";
import { BookOpenCheck, CircleHelp, Scale, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { PageHeader } from "@/components/common/page-header";
import { discoveryQuestions } from "@/data/discovery-questions";

export default function PlaybookPage() {
  return <main className="app"><AppShell /><section className="workspace"><PageHeader eyebrow="APPROVED PLAYBOOK" title="The consultative growth conversation" description="A focused framework based on the uploaded Merchant Growth Guide and AM outreach scripts." /><section className="framework"><Framework number="01" title="Diagnose" text="Ask what the merchant wants to improve: visibility, new customers, larger baskets, repeat orders, or a slow daypart." icon={<CircleHelp size={21} />} /><Framework number="02" title="Match the tool" text="Recommend one primary solution based on the goal. Do not lead with every product." icon={<Scale size={21} />} /><Framework number="03" title="Make it concrete" text="Use the campaign estimate, target audience, schedule, and budget to show how the plan could fit." icon={<BookOpenCheck size={21} />} /><Framework number="04" title="Confirm next step" text="Ask for a decision or a clearly-defined follow-up using a consultative close." icon={<ShieldCheck size={21} />} /></section><div className="playbook-grid"><article className="panel"><p className="eyebrow">HIGH-IMPACT DISCOVERY</p><h2>Ask only what moves the conversation forward</h2><ol className="question-list">{discoveryQuestions.map((question) => <li key={question}>{question}</li>)}</ol><p className="source">Source: DoorDash Merchant Growth Guide · Recommended call flow · p. 6</p></article><article className="panel"><p className="eyebrow">SOURCE CONTROL</p><h2>How this web app stays safe</h2><ul className="safe-list"><li>Recommendations cite their source and page.</li><li>Expired offers are not available to recommend.</li><li>Confidential programs are excluded from the user experience.</li><li>Unsupported questions return an insufficient-information state.</li><li>Current eligibility and commercial terms require verification.</li></ul></article></div></section></main>;
}
function Framework({ number, title, text, icon }: { number: string; title: string; text: string; icon: ReactNode }) { return <article className="framework-card"><span>{number}</span>{icon}<h3>{title}</h3><p>{text}</p></article>; }
